### ISSUE TITLE
Create a RAG Demo 

### ISSUE THREAD

**Issue by deekob** [build-on-aws/dotnet-fm-playground#4]
Lets create a demo based on this existing python one https://github.com/build-on-aws/llm-rag-vectordb-python 

But in C#

**Comment by jayheavner** [comment]
I realize this is the wrong place to ask this but I'm looking at the SDK reference and there's a reference to a RetrieveAndGenerateRequest method that doesn't seem to exist. https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/BedrockAgentRuntime/TRetrieveAndGenerateRequest.html

Is there another way to do this? I just started looking at this yesterday and I'm trying to find a corner to start pulling on.

**Comment by jayheavner** [comment]
Nevermind, figured it out. I had the wrong namespace. The namespaces BedrockAgent, BedrockRuntime, and BedrockAgentRuntime are easy to mix up.

**Comment by fbouteruche** [comment]
Hi @jayheavner, I was traveling at Web Day in Milan, Italy and I've missed your request.
